# Generated by Django 4.2.3 on 2023-08-01 17:13

import autoslug.fields
import ckeditor.fields
import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateEmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeName', models.CharField(default=None, max_length=50)),
                ('employeeEmail', models.EmailField(default=None, max_length=254)),
                ('employeePhone', models.CharField(default=None, max_length=11)),
                ('employeeCity', models.CharField(default='Unspecified', max_length=25)),
                ('employeeAddress', models.CharField(default=None, max_length=200)),
                ('employeeProfession', models.CharField(blank=True, default='Unspecified', max_length=25, null=True)),
                ('employeeSkills', models.CharField(default=None, max_length=200)),
                ('employeeEducation', models.CharField(default=None, max_length=200)),
                ('employeeWorkExperience', models.CharField(default=None, max_length=200)),
                ('employeeWorkExperienceYear', models.CharField(choices=[('None', 'None'), ('6 Month', '6 Month'), ('1 Year', '1 Year'), ('2-3 years', '2-3 Years'), ('3-5 Years', '3-5 Years'), ('5-7 Years', '5-7 Years'), ('7-10 Years', '7-10 Years'), ('10-12 Years', '10-12 Years'), ('12-15 Years', '12-15 Years'), ('15+ Years', '15+ Years')], default='None', max_length=15)),
                ('employeeLanguages', models.CharField(default='Urdu', max_length=60)),
                ('employeeProfessionalSummary', models.CharField(blank=True, default=None, max_length=300)),
                ('employeeImage', models.ImageField(default=None, upload_to='employeeImages/')),
                ('employeeSlug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='employeeName', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='newJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(default=None, max_length=50)),
                ('jobDescription', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('skillsRequirement', tinymce.models.HTMLField(default=None)),
                ('experienceRequirement', tinymce.models.HTMLField(default=None, null=True)),
                ('educationRequirement', tinymce.models.HTMLField(default=None)),
                ('jobLocation', models.CharField(max_length=100)),
                ('salaryRange', models.IntegerField(blank=True)),
                ('companyName', models.CharField(blank=True, max_length=40)),
                ('jobLevel', models.CharField(default='Intermediate', max_length=40)),
                ('jobType', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship'), ('Temporary', 'Temporary'), ('Contract', 'Contract')], default='Full Time', max_length=40)),
                ('companyDescription', tinymce.models.HTMLField(default=None)),
                ('postJobSlug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='jobTitle', unique=True)),
                ('companyImage', models.ImageField(upload_to='company_image/')),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2023, 8, 1, 17, 13, 53, 625924, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
