# Generated by Django 4.2.3 on 2023-08-01 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newjob',
            name='createdAt',
        ),
    ]
