# Generated by Django 4.2.3 on 2023-08-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_newjob_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createemployeemodel',
            name='employeeCity',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='createemployeemodel',
            name='employeeProfession',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='newjob',
            name='companyDescription',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='newjob',
            name='educationRequirement',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='newjob',
            name='experienceRequirement',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='newjob',
            name='jobDescription',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='newjob',
            name='jobLevel',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Intermediate', max_length=40),
        ),
        migrations.AlterField(
            model_name='newjob',
            name='skillsRequirement',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
