# Generated by Django 4.2.3 on 2023-08-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_createemployeemodel_employeecity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createemployeemodel',
            name='employeeFacebook',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='createemployeemodel',
            name='employeeSkills',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
