# Generated by Django 4.2.3 on 2023-08-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_createemployeemodel_employeefacebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createemployeemodel',
            name='employeeGithub',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='createemployeemodel',
            name='employeeInstagram',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='createemployeemodel',
            name='employeeLinkedIn',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
