# Generated by Django 4.2.4 on 2023-08-05 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_createemployeemodel_employeegithub_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createemployeemodel',
            name='employeeResume',
            field=models.FileField(blank=True, null=True, upload_to='resume/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
