# Generated by Django 4.2.4 on 2023-08-08 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_alter_createemployeemodel_employeeresume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createemployeemodel',
            name='employeeResume',
        ),
    ]
