# Generated by Django 4.2.4 on 2023-08-08 08:41

from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_remove_createemployeemodel_employeeresume'),
    ]

    operations = [
        migrations.AddField(
            model_name='createemployeemodel',
            name='employeeResume',
            field=models.FileField(default=jobs.models.default_resume, upload_to='resume/'),
        ),
    ]
