# Generated by Django 4.2.4 on 2023-08-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_createemployeemodel_employeeresume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createemployeemodel',
            name='employeeResume',
            field=models.FileField(upload_to='resume/'),
        ),
    ]
